FROM node:7

# Add Yarn
RUN apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg && \
    echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -f yarn

ADD docker/dev_entrypoint.sh /usr/bin/dev_entrypoint.sh
RUN chmod +x /usr/bin/dev_entrypoint.sh

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENTRYPOINT ["/usr/bin/dev_entrypoint.sh"]
CMD ["bash"]
